### ISSUE TITLE
No name defined in package.json

### ISSUE THREAD

**Issue by Teknologica** [Rebilly/RebillyAPI#39]
The `name` property  is required in the [package.json](https://github.com/Rebilly/RebillyAPI/blob/master/package.json) if it is to be used as a dependency for other projects. I am unsure if this was omitted by error or if it was intentional. In the former case it should be added to the package.json.

**Comment by adamaltman** [comment]
@RomanGotsiy ?

**Comment by RomanGotsiy** [comment]
@Teknologica, actually it can't be used as a dependency because it is not published to npm. It has property [`private`](https://github.com/Rebilly/RebillyAPI/blob/master/package.json#L13) set as well.
What is the purpose of using this as a dependency? Do you need the spec?

**Comment by RomanGotsiy** [comment]
If yes then I belive we should add a CI step to publish only built spec to npm and don't push sources.
Another thing we should consider is versioning: npm doesn't allow to publish the same version of the spec.

**Comment by Teknologica** [comment]
It can be used even if it is private as long as the repo is accessible. Here's an example in another project:
```
npm i -D git+ssh://git@github.com/Teknologica/voie.git#wildcard
// in this case
npm i -D git+ssh://git@github.com:Rebilly/RebillyAPI.git#tagged-version
```
In terms of versioning you simply need to tag a release. I need either the compiled swagger file or all the definitions as dependencies using npm and webpack. Otherwise we will have to maintain a static copy.

**Comment by RomanGotsiy** [comment]
I believe it would be better to provide compiled swagger.
I will add the CI step to do this. This requires some time. So, for now, I'll add `name` and `version` so you can use it.

@adamaltman how about name `rebilly-openapi-spec` ?
And which version should I specify in package.json? I believe `version` property is required as well for using as a dependency.

**Comment by RomanGotsiy** [comment]
@Teknologica, I've added package name and version to the package.json.
Are you OK with it? Or you still need built swagger?
I'm asking because I don't know your exact use case.

**Comment by slavcodev** [comment]
[offtopic]@RomanGotsiy, please do not commit direct to master[/offtopic]

**Comment by Teknologica** [comment]
@RomanGotsiy thanks that's all I need for now :smiley:

**Comment by RomanGotsiy** [comment]
@slavcodev ok, thanks!
